# Generated by Django 5.2.12 on 2026-03-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_deletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletionrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
